### ISSUE TITLE
META Repo Init

### ISSUE THREAD

**Issue by moul** [gnolang/genesis#1]
- [x] Bootstrap the constitution (components, modular; U.S. Constitution)  
- [ ] Rename the README to Genesis  
- [x] Create a main meta issue (overview with milestones, goals, and a list of challenges and topics)  
- [x] Bootstrap some key topics  
- [x] Link from the monorepo  
- [x] Inform the core team about this space for official discussions on these topics  
- [x] Ensure links with Hackerspace, Atomone, Gno repositories, and roadmap repositories  
- [ ] Move to gnoland gh org

**Comment by moul** [comment]
Link to https://github.com/gnolang/hackerspace/issues/62.

Speak about upcoming working group.

**Comment by n2p5** [comment]
Closing this open issue, our focus has shifted for now, and the actionable items are not relevant.
